# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLCDNumber, QLabel, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 593)
        font = QFont()
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(Qt.TabFocus)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lb_now = QLabel(self.centralwidget)
        self.lb_now.setObjectName(u"lb_now")
        self.lb_now.setGeometry(QRect(10, 10, 771, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 40, 71, 21))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 70, 50, 21))
        self.lcd_total_num = QLCDNumber(self.centralwidget)
        self.lcd_total_num.setObjectName(u"lcd_total_num")
        self.lcd_total_num.setGeometry(QRect(70, 70, 64, 23))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 50, 21))
        self.lcd_sani_num = QLCDNumber(self.centralwidget)
        self.lcd_sani_num.setObjectName(u"lcd_sani_num")
        self.lcd_sani_num.setGeometry(QRect(70, 100, 64, 23))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 130, 50, 21))
        self.lcd_temp_num = QLCDNumber(self.centralwidget)
        self.lcd_temp_num.setObjectName(u"lcd_temp_num")
        self.lcd_temp_num.setGeometry(QRect(70, 130, 64, 23))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 160, 50, 21))
        self.lcd_qr_num = QLCDNumber(self.centralwidget)
        self.lcd_qr_num.setObjectName(u"lcd_qr_num")
        self.lcd_qr_num.setGeometry(QRect(70, 160, 64, 23))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(150, 40, 641, 571))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 20, 131, 81))
        self.radio_cpu = QRadioButton(self.groupBox_4)
        self.radio_cpu.setObjectName(u"radio_cpu")
        self.radio_cpu.setGeometry(QRect(10, 30, 91, 20))
        self.radio_gpu = QRadioButton(self.groupBox_4)
        self.radio_gpu.setObjectName(u"radio_gpu")
        self.radio_gpu.setGeometry(QRect(10, 50, 91, 20))
        self.radio_gpu.setChecked(True)
        self.btn_explain_processor = QPushButton(self.groupBox_4)
        self.btn_explain_processor.setObjectName(u"btn_explain_processor")
        self.btn_explain_processor.setGeometry(QRect(100, 0, 31, 20))
        self.groupBox_5 = QGroupBox(self.tab)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(190, 20, 141, 81))
        self.radio_on = QRadioButton(self.groupBox_5)
        self.radio_on.setObjectName(u"radio_on")
        self.radio_on.setGeometry(QRect(10, 30, 91, 20))
        self.radio_on.setChecked(True)
        self.radio_off = QRadioButton(self.groupBox_5)
        self.radio_off.setObjectName(u"radio_off")
        self.radio_off.setGeometry(QRect(10, 50, 91, 20))
        self.btn_explain_label = QPushButton(self.groupBox_5)
        self.btn_explain_label.setObjectName(u"btn_explain_label")
        self.btn_explain_label.setGeometry(QRect(110, 0, 31, 20))
        self.groupBox_6 = QGroupBox(self.tab)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(360, 20, 120, 131))
        self.alarm_ck_all = QCheckBox(self.groupBox_6)
        self.alarm_ck_all.setObjectName(u"alarm_ck_all")
        self.alarm_ck_all.setGeometry(QRect(10, 40, 76, 20))
        self.alarm_ck_all.setChecked(True)
        self.alarm_ck_siren = QCheckBox(self.groupBox_6)
        self.alarm_ck_siren.setObjectName(u"alarm_ck_siren")
        self.alarm_ck_siren.setGeometry(QRect(10, 60, 76, 20))
        self.alarm_ck_siren.setChecked(True)
        self.alarm_ck_light = QCheckBox(self.groupBox_6)
        self.alarm_ck_light.setObjectName(u"alarm_ck_light")
        self.alarm_ck_light.setGeometry(QRect(10, 80, 76, 20))
        self.alarm_ck_light.setChecked(True)
        self.alarm_ck_msg = QCheckBox(self.groupBox_6)
        self.alarm_ck_msg.setObjectName(u"alarm_ck_msg")
        self.alarm_ck_msg.setGeometry(QRect(10, 100, 76, 20))
        self.alarm_ck_msg.setChecked(True)
        self.btn_explain_alarm = QPushButton(self.groupBox_6)
        self.btn_explain_alarm.setObjectName(u"btn_explain_alarm")
        self.btn_explain_alarm.setGeometry(QRect(90, 0, 31, 20))
        self.groupBox_7 = QGroupBox(self.tab)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(510, 20, 111, 81))
        self.cb_display = QComboBox(self.groupBox_7)
        self.cb_display.addItem("")
        self.cb_display.addItem("")
        self.cb_display.addItem("")
        self.cb_display.setObjectName(u"cb_display")
        self.cb_display.setGeometry(QRect(10, 50, 91, 22))
        self.btn_explain_display = QPushButton(self.groupBox_7)
        self.btn_explain_display.setObjectName(u"btn_explain_display")
        self.btn_explain_display.setGeometry(QRect(80, 0, 31, 20))
        self.groupBox_8 = QGroupBox(self.tab)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(20, 160, 181, 111))
        self.hs_rel = QSlider(self.groupBox_8)
        self.hs_rel.setObjectName(u"hs_rel")
        self.hs_rel.setGeometry(QRect(10, 70, 160, 18))
        self.hs_rel.setMinimum(30)
        self.hs_rel.setMaximum(100)
        self.hs_rel.setValue(50)
        self.hs_rel.setOrientation(Qt.Horizontal)
        self.spin_rel = QSpinBox(self.groupBox_8)
        self.spin_rel.setObjectName(u"spin_rel")
        self.spin_rel.setGeometry(QRect(10, 41, 51, 21))
        self.spin_rel.setMinimum(30)
        self.spin_rel.setMaximum(100)
        self.spin_rel.setValue(50)
        self.btn_explain_reliability = QPushButton(self.groupBox_8)
        self.btn_explain_reliability.setObjectName(u"btn_explain_reliability")
        self.btn_explain_reliability.setGeometry(QRect(150, 0, 31, 20))
        self.pushButton_7 = QPushButton(self.groupBox_8)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(180, 20, 31, 20))
        self.pushButton_6 = QPushButton(self.tab)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(390, 340, 211, 161))
        palette = QPalette()
        brush = QBrush(QColor(0, 120, 215, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush)
        self.pushButton_6.setPalette(palette)
        self.pushButton_6.setIconSize(QSize(16, 16))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(230, 160, 231, 101))
        self.corona_ck_all = QCheckBox(self.groupBox)
        self.corona_ck_all.setObjectName(u"corona_ck_all")
        self.corona_ck_all.setGeometry(QRect(10, 40, 76, 20))
        self.corona_ck_all.setChecked(True)
        self.corona_ck_sani = QCheckBox(self.groupBox)
        self.corona_ck_sani.setObjectName(u"corona_ck_sani")
        self.corona_ck_sani.setGeometry(QRect(10, 70, 76, 20))
        self.corona_ck_sani.setChecked(True)
        self.corona_ck_temp = QCheckBox(self.groupBox)
        self.corona_ck_temp.setObjectName(u"corona_ck_temp")
        self.corona_ck_temp.setGeometry(QRect(80, 70, 76, 20))
        self.corona_ck_temp.setChecked(True)
        self.corona_ck_qr = QCheckBox(self.groupBox)
        self.corona_ck_qr.setObjectName(u"corona_ck_qr")
        self.corona_ck_qr.setGeometry(QRect(150, 70, 76, 20))
        self.corona_ck_qr.setChecked(True)
        self.btn_explain_check = QPushButton(self.groupBox)
        self.btn_explain_check.setObjectName(u"btn_explain_check")
        self.btn_explain_check.setGeometry(QRect(200, 0, 31, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.textBrowser = QTextBrowser(self.tab_2)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 0, 341, 521))
        self.pushButton_9 = QPushButton(self.tab_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(410, 20, 81, 24))
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(410, 70, 131, 24))
        self.tabWidget.addTab(self.tab_2, "")
        self.text_status = QTextBrowser(self.centralwidget)
        self.text_status.setObjectName(u"text_status")
        self.text_status.setGeometry(QRect(0, 300, 151, 281))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 280, 61, 16))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Corona CCTV", None))
        self.lb_now.setText(QCoreApplication.translate("MainWindow", u"\ud604\uc7ac\uc2dc\uac01:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\ubbf8\uac80\uc0ac\uc790 \uc218", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ucd1d\ud569", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc190 \uc18c\ub3c5", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc628\ub3c4\uacc4", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"QR \uccb4\ud06c", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uc138\uc11c", None))
        self.radio_cpu.setText(QCoreApplication.translate("MainWindow", u"CPU", None))
        self.radio_gpu.setText(QCoreApplication.translate("MainWindow", u"GPU", None))
        self.btn_explain_processor.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\ub77c\ubca8 \ud45c\uc2dc \uc720\ubb34", None))
        self.radio_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.radio_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.btn_explain_label.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\uacbd\ubcf4", None))
        self.alarm_ck_all.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub450", None))
        self.alarm_ck_siren.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uc774\ub80c", None))
        self.alarm_ck_light.setText(QCoreApplication.translate("MainWindow", u"\uacbd\uad11\ub4f1", None))
        self.alarm_ck_msg.setText(QCoreApplication.translate("MainWindow", u"\uba54\uc138\uc9c0", None))
        self.btn_explain_alarm.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\ud654\uba74 \ud06c\uae30", None))
        self.cb_display.setItemText(0, QCoreApplication.translate("MainWindow", u"1280x720", None))
        self.cb_display.setItemText(1, QCoreApplication.translate("MainWindow", u"640x480", None))
        self.cb_display.setItemText(2, QCoreApplication.translate("MainWindow", u"640x384", None))

        self.btn_explain_display.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\uc2e0\ub8b0\ub3c4(%)", None))
        self.btn_explain_reliability.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\uac80\uc0ac\ud560 \ucf54\ub85c\ub098 \uc18c\ub3c5 \ud589\uc704", None))
        self.corona_ck_all.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub450", None))
        self.corona_ck_sani.setText(QCoreApplication.translate("MainWindow", u"\uc190 \uc18c\ub3c5", None))
        self.corona_ck_temp.setText(QCoreApplication.translate("MainWindow", u"\uc628\ub3c4\uacc4", None))
        self.corona_ck_qr.setText(QCoreApplication.translate("MainWindow", u"QR \uccb4\ud06c", None))
        self.btn_explain_check.setText(QCoreApplication.translate("MainWindow", u"\uc124\uba85", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uadf8\ub7a8 \uc124\uc815", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\ub85c\uadf8 \ucd08\uae30\ud654", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\ubbf8\uac80\uc0ac \uc778\ubb3c \ud655\uc778", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\ub85c\uadf8", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc124\uc815 \ud658\uacbd", None))
    # retranslateUi

